version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: front-kdc-2024
    ports:
      - '3500:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=https://dev.kdccare.ru
